import glob
from setuptools import find_packages, setup

package_name = 'go2_control'

setup(
    name=package_name,
    version='0.0.0',
    packages=find_packages(exclude=['test']),
    data_files=[
        ('share/ament_index/resource_index/packages',
            ['resource/' + package_name]),
        ('share/' + package_name, ['package.xml']),
        ('share/' + package_name,
            ['README_HESAI_FAKE_TEST.md']),
        ('share/' + package_name,
            ['HESAI_GO2_FIELD_CHECKLIST.md']),
        ('share/' + package_name,
            ['HESAI_GO2_HANDOFF.md']),
        ('share/' + package_name,
            ['FIELD_RUNBOOK_QUICK.md']),
        ('share/' + package_name,
            ['LOCAL_SIM_READINESS.md']),
        ('share/' + package_name,
            ['REAL_ROBOT_FIELD_CHECKLIST.md']),
        ('share/' + package_name,
            ['LIVOX_MID360_MIGRATION.md']),
        ('share/' + package_name,
            ['LIVOX_FIELD_DAY_2026-08-19.md']),
        ('share/' + package_name,
            ['LIVOX_BENCH_DAY_2026-08-20.md']),
        ('share/' + package_name,
            ['LIVOX_AMCL_REPLAY_2026-08-25.md']),
        ('share/' + package_name,
            ['LIVOX_NAV2_REPLAY_2026-08-25.md']),
        ('share/' + package_name,
            ['LIVOX_DEPLOYMENT_PLAN.md']),
        ('share/' + package_name,
            ['LIVOX_PREP_DAY_2026-08-25.md']),
        ('share/' + package_name,
            glob.glob('*.yaml')),
        
        ('share/' + package_name + '/rviz',
            glob.glob('rviz/*.rviz')),

        ('share/' + package_name + '/launch',
            ['launch/go2.launch.py']),
        
        ('share/' + package_name + '/launch',
            ['launch/real.launch.py']),

        ('share/' + package_name + '/launch',
            ['launch/sim.launch.py']),

        ('share/' + package_name + '/launch',
            ['launch/mapping.launch.py']),
        ('share/' + package_name + '/launch',
            ['launch/hesai_fake_scan.launch.py']),
        ('share/' + package_name + '/launch',
            ['launch/hesai_fake_mapping.launch.py']),
        ('share/' + package_name + '/launch',
            ['launch/hesai_3d_mapping.launch.py']),
        ('share/' + package_name + '/launch',
            ['launch/hesai_scan.launch.py']),
        ('share/' + package_name + '/launch',
            ['launch/livox_mid360_driver.launch.py']),
        ('share/' + package_name + '/launch',
            ['launch/livox_fake_scan.launch.py']),
        ('share/' + package_name + '/launch',
            ['launch/livox_scan.launch.py']),
        ('share/' + package_name + '/launch',
            ['launch/livox_mid360_lio.launch.py']),
        ('share/' + package_name + '/launch',
            ['launch/livox_amcl.launch.py']),
        ('share/' + package_name + '/launch',
            ['launch/livox_nav2.launch.py']),
        ('share/' + package_name + '/launch',
            ['launch/livox_slam.launch.py']),
        ('share/' + package_name + '/launch',
            ['launch/livox_robot.launch.py']),
        ('share/' + package_name + '/launch',
            ['launch/livox_ground.launch.py']),
        ('share/' + package_name + '/launch',
            ['launch/nav2_scan_test.launch.py']),
        ('share/' + package_name + '/launch',
            ['launch/costmap_scan_test.launch.py']),
        ('share/' + package_name + '/launch',
            ['launch/sim_safe_drive_test.launch.py']),
        ('share/' + package_name + '/config',
            glob.glob('config/*')),
        ('share/' + package_name + '/urdf',
            ['urdf/robot.urdf']),
        ('share/' + package_name + '/meshes',
            glob.glob('meshes/*')),
        ('share/' + package_name + '/worlds',
            glob.glob('worlds/*')),
        ('share/' + package_name + '/map',
            glob.glob('map/*')),
        ('share/' + package_name + '/models/turtlebot3_burger_sim_safe',
            glob.glob('models/turtlebot3_burger_sim_safe/*.sdf') +
            glob.glob('models/turtlebot3_burger_sim_safe/*.config')),
        ('share/' + package_name + '/models/turtlebot3_burger_sim_safe/meshes',
            glob.glob('models/turtlebot3_burger_sim_safe/meshes/*')),
        ('share/' + package_name + '/models/turtlebot3_waffle_3d_lidar',
            glob.glob('models/turtlebot3_waffle_3d_lidar/*.sdf') +
            glob.glob('models/turtlebot3_waffle_3d_lidar/*.config')),
    ],
    install_requires=['setuptools'],
    zip_safe=True,
    maintainer='usys',
    maintainer_email='usys@todo.todo',
    description='TODO: Package description',
    license='TODO: License declaration',
    extras_require={
        'test': [
            'pytest',
        ],
    },
    entry_points={
        'console_scripts': [
        'send_goal = go2_control.send_goal:main',
        'waypoint_gen = go2_control.waypoint_gen:main',
        'init_pose = go2_control.init_pose:main',
        'main = go2_control.main:main',
        'cmd_vel_node = go2_control.cmd_vel_node:main',
        'cmd_vel_udp_relay = go2_control.cmd_vel_udp_relay:main',
        'unitree_udp_bridge = go2_control.unitree_udp_bridge:main',
        'go2w_read = go2_control.go2w_read:main',
        'Stream = go2_control.Stream:main',
        'camera = go2_control.camera:main',
        'fake_robot = go2_control.fake_robot:main',
        'fake_hesai_xt16 = go2_control.fake_hesai_xt16:main',
        'fake_livox_mid360 = go2_control.fake_livox_mid360:main',
        'gazebo_convert = go2_control.gazebo_convert:main',
        'scan_to_pointcloud = go2_control.scan_to_pointcloud:main',
        'pcd_to_map = go2_control.pcd_to_map:main',
        'livox_grid_map = go2_control.livox_grid_map:main',
        'amcl_drift_check = go2_control.amcl_drift_check:main',
        'bag_clock = go2_control.bag_clock:main',
        'lio_odom_relay = go2_control.lio_odom_relay:main',
        'sensor_watchdog = go2_control.sensor_watchdog:main',
        'apriltag_detect = go2_control.apriltag_detect:main',
        'fake_base = go2_control.fake_base:main',
        'local_check = go2_control.local_check:main',
        'april_localizer = go2_control.april_localizer:main',
        'sim_safe_drive = go2_control.sim_safe_drive:main',
        ],
    },
)
